/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/decode': RouteRecordInfo<'/decode', '/decode', Record<never, never>, Record<never, never>>,
    '/heatmap-area': RouteRecordInfo<'/heatmap-area', '/heatmap-area', Record<never, never>, Record<never, never>>,
    '/heatmap-click': RouteRecordInfo<'/heatmap-click', '/heatmap-click', Record<never, never>, Record<never, never>>,
    '/heatmap-scroll': RouteRecordInfo<'/heatmap-scroll', '/heatmap-scroll', Record<never, never>, Record<never, never>>,
    '/play': RouteRecordInfo<'/play', '/play', Record<never, never>, Record<never, never>>,
    '/save': RouteRecordInfo<'/save', '/save', Record<never, never>, Record<never, never>>,
    '/tm-play': RouteRecordInfo<'/tm-play', '/tm-play', Record<never, never>, Record<never, never>>,
  }
}
